<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'staff', 'action' => 'validatecoupon',), 'default'); ?>';
	var formName='<?= $this->couponForm->getName() ?>';
	$(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
});

<?php $this->headScript()->captureEnd() ?>

<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'strumenti',
                                    ), 
                                    'default',true); 
                                    ?>">< Strumenti</a><br>
    <h3><b>Aggiungi promozione</b></h3>
    <?= $this->couponForm; ?>
    <br>
</div>

