<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'strumenti',
                                    ), 
                                    'default',true); 
                                    ?>">< Strumenti</a><br>
    <h3><b>Aggiungi promozione</b></h3>
    <?= $this->couponForm; ?>
    <br>
</div>

