<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <?php $cat=$this->categoria ?>
    <?php echo $this->generalImg($cat->immagine,'categorie/' ,array('class' => ''));?>
</div>

<div class="container">
  <!-- Example row of columns -->
    <div class="row">
            <div class="col-md-12">
                <?php echo '<h2>' . $cat->nome . '</h2>';
                echo $this->generalImg($cat->immagine,'categorie/' ,array('class' => 'imagefrm'));
                echo '<p>' . $cat->descrizione . '</p>'; ?>
                <p><a class="btn btn-default" href='this' role="button">Mostra i coupon dell'azienda &raquo;</a></p> 
            </div>
	</div>
  <hr>
</div>